app:
  scheduler:
    enable: true
    interval: 300s
    force-check-delay: 10s
  update-properties:
    count: 5
    interval: 1800s

spring:
  application:
    name: scrapper
  datasource:
    url: jdbc:postgresql://localhost:5433/scrapper
    username: postgres
    password: postgres

server:
  port: 8080

logging:
  config: classpath:log4j2-plain.xml

api:
  github:
    base-url: https://api.github.com
  stackoverflow:
    base-url: https://api.stackexchange.com/2.3
  bot:
    base-url: http://localhost:8090

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json
