app:
  telegram-token: ${APP_TELEGRAM_TOKEN}

spring:
  application:
    name: bot
  jackson:
    time-zone: UTC

server:
  port: 8090

logging:
  config: classpath:log4j2-plain.xml

springdoc:
  swagger-ui:
    path: /swagger-ui
  default-produces-media-type: application/json

api:
  scrapper:
    base-url: http://localhost:8080

retry:
  scrapper:
    max-attempts: 5
    delay: 1000
    multiplier: 2
    retry-status-codes: INTERNAL_SERVER_ERROR, BAD_GATEWAY, GATEWAY_TIMEOUT, SERVICE_UNAVAILABLE, FORBIDDEN
